### ISSUE TITLE
关于Session模拟登陆

### ISSUE THREAD

**Issue by liu-hantong** [idealclover/Fxxk-NJU-Class-Evaluator#1]
* Po主你好，我也在尝试写python爬虫，使用Python Session进行了模拟登陆教务网，但屡次尝试无法获取登录界面，程序反馈验证码过期，不知道问题出在哪，不知是否可以帮忙看一下，链接在下，谢谢。
[Python登陆教务网](https://github.com/llht/Python-Spider/blob/master/loginTest.py)

**Comment by idealclover** [comment]
问题出现在两个地方：
1. 验证码图片下载时需要用对应session下载，这是造成bug的主要原因
2. 对于我校教务系统，在登陆之后是不可以在get /login.do这个页面的，get后会被登出，可以用浏览器做一下试验ww

~~对了，电子的学弟啊，记得改一下教务系统的密码2333~~
有其他问题欢迎和我py呦，需要联系方式的话自己找>v<
